language:
  node_js
node_js:
  - 12
services:
  - docker
install:
  - npm install -g codecov
  - npm i
script:
  - cd client && npm run lint && docker build .
  - cd .. && npm run lint && npm audit --audit-level high && docker build .
  - npm test
  - codecov
