language:
  node_js
node_js:
  - 12
install:
  - npm install -g codecov
  - npm i
script:
  - cd client && npm run lint && npm audit --audit-level high
  - cd .. && npm run lint && npm audit --audit-level high
  - npm test
  - codecov
