version: '3'
services:
  pbapi:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_HOST: 'ds036617.mlab.com'
      MONGODB_PORT: 36617
      MONGODB_NAME: 'personal_budget'
      MONGODB_USER: ''
      MONGODB_PSW: ''
  pbclient:
    build: client/
    ports:
      - "8080:8080"
    environment:
      BASE_URL: pbapi
    depends_on:
      - pbapi
